"""Certificate preview and export-readiness services."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
import sqlite3

from app.backend.audit.events import AuditAction, AuditEvent
from app.backend.auth.permissions import Action
from app.backend.certificates.preview import (
    CertificatePreview,
    CertificatePreviewError,
    CertificatePreviewRow,
)
from app.backend.domain.workflow import WorkflowState
from app.backend.persistence.sqlite import (
    SQLiteAuditEventRepository,
    SQLiteCalibrationJobRepository,
    SQLiteMeasurementPointSummaryRepository,
)
from app.backend.services.authentication import resolve_actor_for_action
from app.calculation_engine.common.summary import MeasurementPointSummary


class CertificatePreviewServiceError(ValueError):
    """Raised when a certificate preview cannot be generated safely."""


@dataclass(frozen=True, slots=True)
class CertificatePreviewGeneration:
    preview: CertificatePreview
    audit_event_id: int
    audit_event: AuditEvent


def build_certificate_preview_for_session(
    *,
    connection: sqlite3.Connection,
    session_id: str,
    job_id: str,
    template_version: str,
    software_version: str,
    timestamp: datetime,
) -> CertificatePreviewGeneration:
    """Build a certificate preview from locked summaries after actor resolution."""
    actor = resolve_actor_for_action(
        connection=connection,
        session_id=session_id,
        action=Action.PREVIEW_CERTIFICATE,
        timestamp=timestamp,
    )
    return build_certificate_preview(
        connection=connection,
        job_id=job_id,
        generated_by=actor.user_id,
        template_version=template_version,
        software_version=software_version,
        timestamp=timestamp,
    )


def build_certificate_preview(
    *,
    connection: sqlite3.Connection,
    job_id: str,
    generated_by: str,
    template_version: str,
    software_version: str,
    timestamp: datetime,
) -> CertificatePreviewGeneration:
    """Build and audit a certificate preview from persisted calculation summaries."""
    _require_text(job_id, "Job id")
    _require_text(generated_by, "Generated by")
    _require_text(template_version, "Template version")
    _require_text(software_version, "Software version")
    _require_timezone_aware(timestamp, "Preview timestamp")

    with connection:
        job_repository = SQLiteCalibrationJobRepository(connection, autocommit=False)
        summary_repository = SQLiteMeasurementPointSummaryRepository(
            connection,
            autocommit=False,
        )
        audit_repository = SQLiteAuditEventRepository(connection, autocommit=False)

        job = job_repository.get(job_id)
        if job.state not in {
            WorkflowState.CALCULATED,
            WorkflowState.TECHNICAL_REVIEW,
            WorkflowState.QA_REVIEW,
            WorkflowState.APPROVED,
        }:
            raise CertificatePreviewServiceError(
                "Certificate preview requires calculated or later workflow state."
            )

        summaries = summary_repository.list_for_job(job_id)
        if len(summaries) == 0:
            raise CertificatePreviewServiceError(
                "Certificate preview requires calculation summaries."
            )

        preview = _preview_from_summaries(
            job_id=job_id,
            generated_by=generated_by,
            generated_at=timestamp,
            software_version=software_version,
            template_version=template_version,
            summaries=summaries,
        )
        audit_event = _preview_audit_event(preview)
        audit_event_id = audit_repository.append(audit_event)

    return CertificatePreviewGeneration(
        preview=preview,
        audit_event_id=audit_event_id,
        audit_event=audit_event,
    )


def _preview_from_summaries(
    *,
    job_id: str,
    generated_by: str,
    generated_at: datetime,
    software_version: str,
    template_version: str,
    summaries: tuple[MeasurementPointSummary, ...],
) -> CertificatePreview:
    calculation_engine_version = _single_version(
        {summary.calculation_engine_version for summary in summaries},
        "calculation engine",
    )
    constant_set_version = _single_version(
        {summary.constant_set_version for summary in summaries},
        "constant set",
    )
    budget_version = _single_version(
        {summary.budget_version for summary in summaries},
        "budget",
    )
    try:
        return CertificatePreview(
            job_id=job_id,
            generated_by=generated_by,
            generated_at=generated_at,
            software_version=software_version,
            calculation_engine_version=calculation_engine_version,
            constant_set_version=constant_set_version,
            budget_version=budget_version,
            template_version=template_version,
            rows=tuple(_preview_row(summary) for summary in summaries),
        )
    except CertificatePreviewError as exc:
        raise CertificatePreviewServiceError(str(exc)) from exc


def _preview_row(summary: MeasurementPointSummary) -> CertificatePreviewRow:
    return CertificatePreviewRow(
        point_id=summary.point_id,
        dut_id=summary.dut_id,
        measurement_window_id=summary.measurement_window_id,
        reference=summary.reference,
        indication=summary.indication,
        error_of_indication=summary.error_of_indication,
        display_error_of_indication=summary.display_error_of_indication,
        reported_expanded_uncertainty=summary.reported_expanded_uncertainty,
        unit=summary.unit,
    )


def _preview_audit_event(preview: CertificatePreview) -> AuditEvent:
    return AuditEvent(
        entity_type="calibration_job",
        entity_id=preview.job_id,
        action=AuditAction.CERTIFICATE_PREVIEW_GENERATED,
        user_id=preview.generated_by,
        timestamp=preview.generated_at,
        new_value={
            "summary_ids": list(preview.summary_ids),
            "row_count": len(preview.rows),
            "template_version": preview.template_version,
        },
        software_version=preview.software_version,
        calculation_engine_version=preview.calculation_engine_version,
        constant_set_version=preview.constant_set_version,
        budget_version=preview.budget_version,
    )


def _single_version(versions: set[str], label: str) -> str:
    if len(versions) != 1:
        raise CertificatePreviewServiceError(
            f"Certificate preview requires one {label} version across summaries."
        )
    return next(iter(versions))


def _require_text(value: str, field_name: str) -> None:
    if value.strip() == "":
        raise CertificatePreviewServiceError(f"{field_name} is required.")


def _require_timezone_aware(value: datetime, field_name: str) -> None:
    if value.tzinfo is None or value.utcoffset() is None:
        raise CertificatePreviewServiceError(f"{field_name} must be timezone-aware.")
